baseURL = "https://amckim2022.github.io/"
publishDir = "docs"
languageCode = "en-us"
title = "Ashley McKim's Website"
theme = "PaperMod"

[params]
  description = "About me, projects, and resume"

  [params.homeInfoParams]
    Title = "Ashley McKim's Website"
    Content = "About me, projects, and resume"

  [[params.socialIcons]]
    name = "email"
    url  = "mailto:amckim2022@my.fit.edu"

[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url  = "/posts/"
    weight = 3
