baseURL = 'https://amckim2022.github.io/'
publishDir = "docs"
languageCode = 'en-us'
[params.homeInfoParams]
    title = 'Ashley McKim's Website'
    Content = "About me, projects, and resume"
theme = "PaperMod"

# hugo.toml
[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

  [[menu.main]]
    name = "About me"
    url  = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url  = "/about/"
    weight = 3

[[params.socialIcons]]
name = "Email"
url  = "amckim2022@my.fit.edu"


